# Generated by Django 5.0.14 on 2025-11-09 02:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField()),
                ('challenge_type', models.CharField(choices=[('regular', 'Regular'), ('exclusive', 'Exclusive'), ('decreasing', 'Decreasing'), ('dependent', 'Dependent')], default='regular', max_length=20)),
                ('base_points', models.PositiveIntegerField(default=100)),
                ('decay_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Percentage (0-100) deducted for remaining classes each time this challenge is solved.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('minimum_points', models.PositiveIntegerField(default=0, help_text='Floor value for decreasing challenges when decay is applied.')),
                ('answer', models.TextField(help_text='Exact answer string that must be submitted to award credit.')),
                ('answer_case_sensitive', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple_solves', models.BooleanField(default=False, help_text='Reserved for future modes; remains False so only one solve per class.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='core.challengecategory')),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.challenge')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocking', to='core.challenge')),
            ],
            options={
                'unique_together': {('challenge', 'prerequisite')},
            },
        ),
        migrations.AddField(
            model_name='challenge',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='unlocking_challenges', through='core.ChallengeDependency', to='core.challenge'),
        ),
        migrations.CreateModel(
            name='ChallengeSolve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_year', models.PositiveIntegerField(help_text='Graduation year representing the solving class.')),
                ('awarded_points', models.IntegerField()),
                ('submitted_answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solves', to='core.challenge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_solves', to='core.participant')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('challenge', 'team_year')},
            },
        ),
    ]
