# Generated by Django 5.0.14 on 2025-11-09 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_challengecategory_challenge_challengedependency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenge',
            options={'ordering': ['category', 'sort_order', 'title']},
        ),
        migrations.AddField(
            model_name='challenge',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls display order within the category (lower numbers appear first).'),
        ),
    ]
