# Generated by Django 5.0.14 on 2025-12-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_challenge_options_challenge_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True, help_text='Discord webhook URL for first blood notifications', max_length=500)),
                ('notifications_enabled', models.BooleanField(default=False, help_text='Enable/disable Discord first blood notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord Settings',
                'verbose_name_plural': 'Discord Settings',
            },
        ),
    ]
