# Generated by Django 5.0.14 on 2026-01-03 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_discordsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='is_scavcomm',
            field=models.BooleanField(default=False, help_text='Scavcomm members can view analytics but cannot access Django admin.'),
        ),
    ]
